data:
    train : /kaggle/working/scierc/data/train.txt
    test : /kaggle/working/scierc/data/test.txt
    dev: /kaggle/working/scierc/data/dev.txt
    finetuned_model: /kaggle/working/scierc/model/

finetunedmodel:
    model : /kaggle/working/scierc/model/pytorch_model.bin
    config: /kaggle/working/scierc/model/config.json
    vocab: /kaggle/working/scierc/model/

hyperparams:
     learning_rate: 2e-5
     epsilon: 1e-8
     epochs: 3
     batch_size: 64
