data:
    train : /kaggle/working/fine-tune-bert-on-biomed/data/train.txt
    test : /kaggle/working/fine-tune-bert-on-biomed/data/test.txt
    dev: /kaggle/working/fine-tune-bert-on-biomed/data/dev.txt
    finetuned_model: /kaggle/working/fine-tune-bert-on-biomed/model/

finetunedmodel:
    model : /kaggle/working/fine-tune-bert-on-biomed/model/pytorch_model.bin
    config: /kaggle/working/fine-tune-bert-on-biomed/model/config.json
    vocab: /kaggle/working/fine-tune-bert-on-biomed/model/vocab.txt

hyperparams:
     learning_rate: 2e-5
     epsilon: 1e-8
     epochs: 1
     batch_size: 64
